### ISSUE TITLE
TypeError Issue

### ISSUE THREAD

**Issue by RedPxnda** [Prunoideae/ProbeJS-Forge#2]
![image](https://user-images.githubusercontent.com/54185270/157995380-2725f7d8-c83b-4c2a-ac9c-5d59f5f34ac8.png)
/reload brings up that error, not much else to say.

**Comment by Prunoideae** [comment]
for my own usage i wrote a tag member dump before, (in that dump.js), which exports a tag const of all tags. it seems that predefining namespaces is not a good idea, gonna remove the feature later

**Comment by Prunoideae** [comment]
fixed.
